// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.27.3
// source: shredstream.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Shredstream_SendHeartbeat_FullMethodName = "/shredstream.Shredstream/SendHeartbeat"
)

// ShredstreamClient is the client API for Shredstream service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ShredstreamClient interface {
	// RPC endpoint to send heartbeats to keep shreds flowing
	SendHeartbeat(ctx context.Context, in *ShredstreamHeartbeat, opts ...grpc.CallOption) (*ShredstreamHeartbeatResponse, error)
}

type shredstreamClient struct {
	cc grpc.ClientConnInterface
}

func NewShredstreamClient(cc grpc.ClientConnInterface) ShredstreamClient {
	return &shredstreamClient{cc}
}

func (c *shredstreamClient) SendHeartbeat(ctx context.Context, in *ShredstreamHeartbeat, opts ...grpc.CallOption) (*ShredstreamHeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShredstreamHeartbeatResponse)
	err := c.cc.Invoke(ctx, Shredstream_SendHeartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ShredstreamServer is the server API for Shredstream service.
// All implementations must embed UnimplementedShredstreamServer
// for forward compatibility.
type ShredstreamServer interface {
	// RPC endpoint to send heartbeats to keep shreds flowing
	SendHeartbeat(context.Context, *ShredstreamHeartbeat) (*ShredstreamHeartbeatResponse, error)
	mustEmbedUnimplementedShredstreamServer()
}

// UnimplementedShredstreamServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedShredstreamServer struct{}

func (UnimplementedShredstreamServer) SendHeartbeat(context.Context, *ShredstreamHeartbeat) (*ShredstreamHeartbeatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendHeartbeat not implemented")
}
func (UnimplementedShredstreamServer) mustEmbedUnimplementedShredstreamServer() {}
func (UnimplementedShredstreamServer) testEmbeddedByValue()                     {}

// UnsafeShredstreamServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ShredstreamServer will
// result in compilation errors.
type UnsafeShredstreamServer interface {
	mustEmbedUnimplementedShredstreamServer()
}

func RegisterShredstreamServer(s grpc.ServiceRegistrar, srv ShredstreamServer) {
	// If the following call panics, it indicates UnimplementedShredstreamServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Shredstream_ServiceDesc, srv)
}

func _Shredstream_SendHeartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShredstreamHeartbeat)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShredstreamServer).SendHeartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Shredstream_SendHeartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShredstreamServer).SendHeartbeat(ctx, req.(*ShredstreamHeartbeat))
	}
	return interceptor(ctx, in, info, handler)
}

// Shredstream_ServiceDesc is the grpc.ServiceDesc for Shredstream service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Shredstream_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "shredstream.Shredstream",
	HandlerType: (*ShredstreamServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendHeartbeat",
			Handler:    _Shredstream_SendHeartbeat_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "shredstream.proto",
}

const (
	ShredstreamProxy_SubscribeEntries_FullMethodName            = "/shredstream.ShredstreamProxy/SubscribeEntries"
	ShredstreamProxy_SubscribeParsedTransactions_FullMethodName = "/shredstream.ShredstreamProxy/SubscribeParsedTransactions"
)

// ShredstreamProxyClient is the client API for ShredstreamProxy service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ShredstreamProxyClient interface {
	SubscribeEntries(ctx context.Context, in *SubscribeEntriesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Entry], error)
	SubscribeParsedTransactions(ctx context.Context, in *SubscribeParsedRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ParsedTransaction], error)
}

type shredstreamProxyClient struct {
	cc grpc.ClientConnInterface
}

func NewShredstreamProxyClient(cc grpc.ClientConnInterface) ShredstreamProxyClient {
	return &shredstreamProxyClient{cc}
}

func (c *shredstreamProxyClient) SubscribeEntries(ctx context.Context, in *SubscribeEntriesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Entry], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ShredstreamProxy_ServiceDesc.Streams[0], ShredstreamProxy_SubscribeEntries_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeEntriesRequest, Entry]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ShredstreamProxy_SubscribeEntriesClient = grpc.ServerStreamingClient[Entry]

func (c *shredstreamProxyClient) SubscribeParsedTransactions(ctx context.Context, in *SubscribeParsedRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ParsedTransaction], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ShredstreamProxy_ServiceDesc.Streams[1], ShredstreamProxy_SubscribeParsedTransactions_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeParsedRequest, ParsedTransaction]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ShredstreamProxy_SubscribeParsedTransactionsClient = grpc.ServerStreamingClient[ParsedTransaction]

// ShredstreamProxyServer is the server API for ShredstreamProxy service.
// All implementations must embed UnimplementedShredstreamProxyServer
// for forward compatibility.
type ShredstreamProxyServer interface {
	SubscribeEntries(*SubscribeEntriesRequest, grpc.ServerStreamingServer[Entry]) error
	SubscribeParsedTransactions(*SubscribeParsedRequest, grpc.ServerStreamingServer[ParsedTransaction]) error
	mustEmbedUnimplementedShredstreamProxyServer()
}

// UnimplementedShredstreamProxyServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedShredstreamProxyServer struct{}

func (UnimplementedShredstreamProxyServer) SubscribeEntries(*SubscribeEntriesRequest, grpc.ServerStreamingServer[Entry]) error {
	return status.Error(codes.Unimplemented, "method SubscribeEntries not implemented")
}
func (UnimplementedShredstreamProxyServer) SubscribeParsedTransactions(*SubscribeParsedRequest, grpc.ServerStreamingServer[ParsedTransaction]) error {
	return status.Error(codes.Unimplemented, "method SubscribeParsedTransactions not implemented")
}
func (UnimplementedShredstreamProxyServer) mustEmbedUnimplementedShredstreamProxyServer() {}
func (UnimplementedShredstreamProxyServer) testEmbeddedByValue()                          {}

// UnsafeShredstreamProxyServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ShredstreamProxyServer will
// result in compilation errors.
type UnsafeShredstreamProxyServer interface {
	mustEmbedUnimplementedShredstreamProxyServer()
}

func RegisterShredstreamProxyServer(s grpc.ServiceRegistrar, srv ShredstreamProxyServer) {
	// If the following call panics, it indicates UnimplementedShredstreamProxyServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ShredstreamProxy_ServiceDesc, srv)
}

func _ShredstreamProxy_SubscribeEntries_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeEntriesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ShredstreamProxyServer).SubscribeEntries(m, &grpc.GenericServerStream[SubscribeEntriesRequest, Entry]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ShredstreamProxy_SubscribeEntriesServer = grpc.ServerStreamingServer[Entry]

func _ShredstreamProxy_SubscribeParsedTransactions_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeParsedRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ShredstreamProxyServer).SubscribeParsedTransactions(m, &grpc.GenericServerStream[SubscribeParsedRequest, ParsedTransaction]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ShredstreamProxy_SubscribeParsedTransactionsServer = grpc.ServerStreamingServer[ParsedTransaction]

// ShredstreamProxy_ServiceDesc is the grpc.ServiceDesc for ShredstreamProxy service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ShredstreamProxy_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "shredstream.ShredstreamProxy",
	HandlerType: (*ShredstreamProxyServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeEntries",
			Handler:       _ShredstreamProxy_SubscribeEntries_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SubscribeParsedTransactions",
			Handler:       _ShredstreamProxy_SubscribeParsedTransactions_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "shredstream.proto",
}
