// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.27.3
// source: shredstream.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JitoSocket struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Port          int64                  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JitoSocket) Reset() {
	*x = JitoSocket{}
	mi := &file_shredstream_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JitoSocket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JitoSocket) ProtoMessage() {}

func (x *JitoSocket) ProtoReflect() protoreflect.Message {
	mi := &file_shredstream_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JitoSocket.ProtoReflect.Descriptor instead.
func (*JitoSocket) Descriptor() ([]byte, []int) {
	return file_shredstream_proto_rawDescGZIP(), []int{0}
}

func (x *JitoSocket) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *JitoSocket) GetPort() int64 {
	if x != nil {
		return x.Port
	}
	return 0
}

type JitoHeartbeat struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// don't trust IP:PORT from tcp header since it can be tampered over the wire
	// `socket.ip` must match incoming packet's ip. this prevents spamming an unwitting destination
	Socket *JitoSocket `protobuf:"bytes,1,opt,name=socket,proto3" json:"socket,omitempty"`
	// regions for shredstream proxy to receive shreds from
	// list of valid regions: https://docs.jito.wtf/lowlatencytxnsend/#api
	Regions       []string `protobuf:"bytes,2,rep,name=regions,proto3" json:"regions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JitoHeartbeat) Reset() {
	*x = JitoHeartbeat{}
	mi := &file_shredstream_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JitoHeartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JitoHeartbeat) ProtoMessage() {}

func (x *JitoHeartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_shredstream_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JitoHeartbeat.ProtoReflect.Descriptor instead.
func (*JitoHeartbeat) Descriptor() ([]byte, []int) {
	return file_shredstream_proto_rawDescGZIP(), []int{1}
}

func (x *JitoHeartbeat) GetSocket() *JitoSocket {
	if x != nil {
		return x.Socket
	}
	return nil
}

func (x *JitoHeartbeat) GetRegions() []string {
	if x != nil {
		return x.Regions
	}
	return nil
}

type JitoHeartbeatResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// client must respond within `ttl_ms` to keep stream alive
	TtlMs         uint32 `protobuf:"varint,1,opt,name=ttl_ms,json=ttlMs,proto3" json:"ttl_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JitoHeartbeatResponse) Reset() {
	*x = JitoHeartbeatResponse{}
	mi := &file_shredstream_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JitoHeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JitoHeartbeatResponse) ProtoMessage() {}

func (x *JitoHeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shredstream_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JitoHeartbeatResponse.ProtoReflect.Descriptor instead.
func (*JitoHeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_shredstream_proto_rawDescGZIP(), []int{2}
}

func (x *JitoHeartbeatResponse) GetTtlMs() uint32 {
	if x != nil {
		return x.TtlMs
	}
	return 0
}

type JitoTraceShred struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// source region, one of: https://docs.jito.wtf/lowlatencytxnsend/#api
	Region string `protobuf:"bytes,1,opt,name=region,proto3" json:"region,omitempty"`
	// timestamp of creation
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// monotonically increases, resets upon service restart
	SeqNum        uint32 `protobuf:"varint,3,opt,name=seq_num,json=seqNum,proto3" json:"seq_num,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JitoTraceShred) Reset() {
	*x = JitoTraceShred{}
	mi := &file_shredstream_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JitoTraceShred) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JitoTraceShred) ProtoMessage() {}

func (x *JitoTraceShred) ProtoReflect() protoreflect.Message {
	mi := &file_shredstream_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JitoTraceShred.ProtoReflect.Descriptor instead.
func (*JitoTraceShred) Descriptor() ([]byte, []int) {
	return file_shredstream_proto_rawDescGZIP(), []int{3}
}

func (x *JitoTraceShred) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *JitoTraceShred) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *JitoTraceShred) GetSeqNum() uint32 {
	if x != nil {
		return x.SeqNum
	}
	return 0
}

type JitoSubscribeEntriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JitoSubscribeEntriesRequest) Reset() {
	*x = JitoSubscribeEntriesRequest{}
	mi := &file_shredstream_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JitoSubscribeEntriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JitoSubscribeEntriesRequest) ProtoMessage() {}

func (x *JitoSubscribeEntriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shredstream_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JitoSubscribeEntriesRequest.ProtoReflect.Descriptor instead.
func (*JitoSubscribeEntriesRequest) Descriptor() ([]byte, []int) {
	return file_shredstream_proto_rawDescGZIP(), []int{4}
}

type JitoEntry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// the slot that the entry is from
	Slot uint64 `protobuf:"varint,1,opt,name=slot,proto3" json:"slot,omitempty"`
	// Serialized bytes of Vec<Entry>: https://docs.rs/solana-entry/latest/solana_entry/entry/struct.Entry.html
	Entries       []byte `protobuf:"bytes,2,opt,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JitoEntry) Reset() {
	*x = JitoEntry{}
	mi := &file_shredstream_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JitoEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JitoEntry) ProtoMessage() {}

func (x *JitoEntry) ProtoReflect() protoreflect.Message {
	mi := &file_shredstream_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JitoEntry.ProtoReflect.Descriptor instead.
func (*JitoEntry) Descriptor() ([]byte, []int) {
	return file_shredstream_proto_rawDescGZIP(), []int{5}
}

func (x *JitoEntry) GetSlot() uint64 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *JitoEntry) GetEntries() []byte {
	if x != nil {
		return x.Entries
	}
	return nil
}

var File_shredstream_proto protoreflect.FileDescriptor

const file_shredstream_proto_rawDesc = "" +
	"\n" +
	"\x11shredstream.proto\x12\x0fjitoshredstream\x1a\x1fgoogle/protobuf/timestamp.proto\"0\n" +
	"\n" +
	"JitoSocket\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\x12\x12\n" +
	"\x04port\x18\x02 \x01(\x03R\x04port\"^\n" +
	"\rJitoHeartbeat\x123\n" +
	"\x06socket\x18\x01 \x01(\v2\x1b.jitoshredstream.JitoSocketR\x06socket\x12\x18\n" +
	"\aregions\x18\x02 \x03(\tR\aregions\".\n" +
	"\x15JitoHeartbeatResponse\x12\x15\n" +
	"\x06ttl_ms\x18\x01 \x01(\rR\x05ttlMs\"|\n" +
	"\x0eJitoTraceShred\x12\x16\n" +
	"\x06region\x18\x01 \x01(\tR\x06region\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x17\n" +
	"\aseq_num\x18\x03 \x01(\rR\x06seqNum\"\x1d\n" +
	"\x1bJitoSubscribeEntriesRequest\"9\n" +
	"\tJitoEntry\x12\x12\n" +
	"\x04slot\x18\x01 \x01(\x04R\x04slot\x12\x18\n" +
	"\aentries\x18\x02 \x01(\fR\aentries2l\n" +
	"\x0fJitoShredstream\x12Y\n" +
	"\rSendHeartbeat\x12\x1e.jitoshredstream.JitoHeartbeat\x1a&.jitoshredstream.JitoHeartbeatResponse\"\x002v\n" +
	"\x14JitoShredstreamProxy\x12^\n" +
	"\x10SubscribeEntries\x12,.jitoshredstream.JitoSubscribeEntriesRequest\x1a\x1a.jitoshredstream.JitoEntry0\x01B\x15Z\x13/jitoshredstream/pbb\x06proto3"

var (
	file_shredstream_proto_rawDescOnce sync.Once
	file_shredstream_proto_rawDescData []byte
)

func file_shredstream_proto_rawDescGZIP() []byte {
	file_shredstream_proto_rawDescOnce.Do(func() {
		file_shredstream_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shredstream_proto_rawDesc), len(file_shredstream_proto_rawDesc)))
	})
	return file_shredstream_proto_rawDescData
}

var file_shredstream_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_shredstream_proto_goTypes = []any{
	(*JitoSocket)(nil),                  // 0: jitoshredstream.JitoSocket
	(*JitoHeartbeat)(nil),               // 1: jitoshredstream.JitoHeartbeat
	(*JitoHeartbeatResponse)(nil),       // 2: jitoshredstream.JitoHeartbeatResponse
	(*JitoTraceShred)(nil),              // 3: jitoshredstream.JitoTraceShred
	(*JitoSubscribeEntriesRequest)(nil), // 4: jitoshredstream.JitoSubscribeEntriesRequest
	(*JitoEntry)(nil),                   // 5: jitoshredstream.JitoEntry
	(*timestamppb.Timestamp)(nil),       // 6: google.protobuf.Timestamp
}
var file_shredstream_proto_depIdxs = []int32{
	0, // 0: jitoshredstream.JitoHeartbeat.socket:type_name -> jitoshredstream.JitoSocket
	6, // 1: jitoshredstream.JitoTraceShred.created_at:type_name -> google.protobuf.Timestamp
	1, // 2: jitoshredstream.JitoShredstream.SendHeartbeat:input_type -> jitoshredstream.JitoHeartbeat
	4, // 3: jitoshredstream.JitoShredstreamProxy.SubscribeEntries:input_type -> jitoshredstream.JitoSubscribeEntriesRequest
	2, // 4: jitoshredstream.JitoShredstream.SendHeartbeat:output_type -> jitoshredstream.JitoHeartbeatResponse
	5, // 5: jitoshredstream.JitoShredstreamProxy.SubscribeEntries:output_type -> jitoshredstream.JitoEntry
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_shredstream_proto_init() }
func file_shredstream_proto_init() {
	if File_shredstream_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shredstream_proto_rawDesc), len(file_shredstream_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_shredstream_proto_goTypes,
		DependencyIndexes: file_shredstream_proto_depIdxs,
		MessageInfos:      file_shredstream_proto_msgTypes,
	}.Build()
	File_shredstream_proto = out.File
	file_shredstream_proto_goTypes = nil
	file_shredstream_proto_depIdxs = nil
}
