// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.27.3
// source: shredstream.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	JitoShredstream_SendHeartbeat_FullMethodName = "/jitoshredstream.JitoShredstream/SendHeartbeat"
)

// JitoShredstreamClient is the client API for JitoShredstream service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type JitoShredstreamClient interface {
	// RPC endpoint to send heartbeats to keep shreds flowing
	SendHeartbeat(ctx context.Context, in *JitoHeartbeat, opts ...grpc.CallOption) (*JitoHeartbeatResponse, error)
}

type jitoShredstreamClient struct {
	cc grpc.ClientConnInterface
}

func NewJitoShredstreamClient(cc grpc.ClientConnInterface) JitoShredstreamClient {
	return &jitoShredstreamClient{cc}
}

func (c *jitoShredstreamClient) SendHeartbeat(ctx context.Context, in *JitoHeartbeat, opts ...grpc.CallOption) (*JitoHeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JitoHeartbeatResponse)
	err := c.cc.Invoke(ctx, JitoShredstream_SendHeartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// JitoShredstreamServer is the server API for JitoShredstream service.
// All implementations must embed UnimplementedJitoShredstreamServer
// for forward compatibility.
type JitoShredstreamServer interface {
	// RPC endpoint to send heartbeats to keep shreds flowing
	SendHeartbeat(context.Context, *JitoHeartbeat) (*JitoHeartbeatResponse, error)
	mustEmbedUnimplementedJitoShredstreamServer()
}

// UnimplementedJitoShredstreamServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedJitoShredstreamServer struct{}

func (UnimplementedJitoShredstreamServer) SendHeartbeat(context.Context, *JitoHeartbeat) (*JitoHeartbeatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendHeartbeat not implemented")
}
func (UnimplementedJitoShredstreamServer) mustEmbedUnimplementedJitoShredstreamServer() {}
func (UnimplementedJitoShredstreamServer) testEmbeddedByValue()                         {}

// UnsafeJitoShredstreamServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to JitoShredstreamServer will
// result in compilation errors.
type UnsafeJitoShredstreamServer interface {
	mustEmbedUnimplementedJitoShredstreamServer()
}

func RegisterJitoShredstreamServer(s grpc.ServiceRegistrar, srv JitoShredstreamServer) {
	// If the following call panics, it indicates UnimplementedJitoShredstreamServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&JitoShredstream_ServiceDesc, srv)
}

func _JitoShredstream_SendHeartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JitoHeartbeat)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JitoShredstreamServer).SendHeartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JitoShredstream_SendHeartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JitoShredstreamServer).SendHeartbeat(ctx, req.(*JitoHeartbeat))
	}
	return interceptor(ctx, in, info, handler)
}

// JitoShredstream_ServiceDesc is the grpc.ServiceDesc for JitoShredstream service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var JitoShredstream_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "jitoshredstream.JitoShredstream",
	HandlerType: (*JitoShredstreamServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendHeartbeat",
			Handler:    _JitoShredstream_SendHeartbeat_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "shredstream.proto",
}

const (
	JitoShredstreamProxy_SubscribeEntries_FullMethodName = "/jitoshredstream.JitoShredstreamProxy/SubscribeEntries"
)

// JitoShredstreamProxyClient is the client API for JitoShredstreamProxy service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type JitoShredstreamProxyClient interface {
	SubscribeEntries(ctx context.Context, in *JitoSubscribeEntriesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[JitoEntry], error)
}

type jitoShredstreamProxyClient struct {
	cc grpc.ClientConnInterface
}

func NewJitoShredstreamProxyClient(cc grpc.ClientConnInterface) JitoShredstreamProxyClient {
	return &jitoShredstreamProxyClient{cc}
}

func (c *jitoShredstreamProxyClient) SubscribeEntries(ctx context.Context, in *JitoSubscribeEntriesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[JitoEntry], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &JitoShredstreamProxy_ServiceDesc.Streams[0], JitoShredstreamProxy_SubscribeEntries_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[JitoSubscribeEntriesRequest, JitoEntry]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type JitoShredstreamProxy_SubscribeEntriesClient = grpc.ServerStreamingClient[JitoEntry]

// JitoShredstreamProxyServer is the server API for JitoShredstreamProxy service.
// All implementations must embed UnimplementedJitoShredstreamProxyServer
// for forward compatibility.
type JitoShredstreamProxyServer interface {
	SubscribeEntries(*JitoSubscribeEntriesRequest, grpc.ServerStreamingServer[JitoEntry]) error
	mustEmbedUnimplementedJitoShredstreamProxyServer()
}

// UnimplementedJitoShredstreamProxyServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedJitoShredstreamProxyServer struct{}

func (UnimplementedJitoShredstreamProxyServer) SubscribeEntries(*JitoSubscribeEntriesRequest, grpc.ServerStreamingServer[JitoEntry]) error {
	return status.Error(codes.Unimplemented, "method SubscribeEntries not implemented")
}
func (UnimplementedJitoShredstreamProxyServer) mustEmbedUnimplementedJitoShredstreamProxyServer() {}
func (UnimplementedJitoShredstreamProxyServer) testEmbeddedByValue()                              {}

// UnsafeJitoShredstreamProxyServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to JitoShredstreamProxyServer will
// result in compilation errors.
type UnsafeJitoShredstreamProxyServer interface {
	mustEmbedUnimplementedJitoShredstreamProxyServer()
}

func RegisterJitoShredstreamProxyServer(s grpc.ServiceRegistrar, srv JitoShredstreamProxyServer) {
	// If the following call panics, it indicates UnimplementedJitoShredstreamProxyServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&JitoShredstreamProxy_ServiceDesc, srv)
}

func _JitoShredstreamProxy_SubscribeEntries_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(JitoSubscribeEntriesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(JitoShredstreamProxyServer).SubscribeEntries(m, &grpc.GenericServerStream[JitoSubscribeEntriesRequest, JitoEntry]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type JitoShredstreamProxy_SubscribeEntriesServer = grpc.ServerStreamingServer[JitoEntry]

// JitoShredstreamProxy_ServiceDesc is the grpc.ServiceDesc for JitoShredstreamProxy service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var JitoShredstreamProxy_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "jitoshredstream.JitoShredstreamProxy",
	HandlerType: (*JitoShredstreamProxyServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeEntries",
			Handler:       _JitoShredstreamProxy_SubscribeEntries_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "shredstream.proto",
}
