// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.27.3
// source: shredstream.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ShredstreamSocket struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Port          int64                  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShredstreamSocket) Reset() {
	*x = ShredstreamSocket{}
	mi := &file_shredstream_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShredstreamSocket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShredstreamSocket) ProtoMessage() {}

func (x *ShredstreamSocket) ProtoReflect() protoreflect.Message {
	mi := &file_shredstream_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShredstreamSocket.ProtoReflect.Descriptor instead.
func (*ShredstreamSocket) Descriptor() ([]byte, []int) {
	return file_shredstream_proto_rawDescGZIP(), []int{0}
}

func (x *ShredstreamSocket) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *ShredstreamSocket) GetPort() int64 {
	if x != nil {
		return x.Port
	}
	return 0
}

type ShredstreamHeartbeat struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// don't trust IP:PORT from tcp header since it can be tampered over the wire
	// `socket.ip` must match incoming packet's ip. this prevents spamming an unwitting destination
	Socket *ShredstreamSocket `protobuf:"bytes,1,opt,name=socket,proto3" json:"socket,omitempty"`
	// regions for shredstream proxy to receive shreds from
	// list of valid regions: https://docs.jito.wtf/lowlatencytxnsend/#api
	Regions       []string `protobuf:"bytes,2,rep,name=regions,proto3" json:"regions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShredstreamHeartbeat) Reset() {
	*x = ShredstreamHeartbeat{}
	mi := &file_shredstream_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShredstreamHeartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShredstreamHeartbeat) ProtoMessage() {}

func (x *ShredstreamHeartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_shredstream_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShredstreamHeartbeat.ProtoReflect.Descriptor instead.
func (*ShredstreamHeartbeat) Descriptor() ([]byte, []int) {
	return file_shredstream_proto_rawDescGZIP(), []int{1}
}

func (x *ShredstreamHeartbeat) GetSocket() *ShredstreamSocket {
	if x != nil {
		return x.Socket
	}
	return nil
}

func (x *ShredstreamHeartbeat) GetRegions() []string {
	if x != nil {
		return x.Regions
	}
	return nil
}

type ShredstreamHeartbeatResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// client must respond within `ttl_ms` to keep stream alive
	TtlMs         uint32 `protobuf:"varint,1,opt,name=ttl_ms,json=ttlMs,proto3" json:"ttl_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShredstreamHeartbeatResponse) Reset() {
	*x = ShredstreamHeartbeatResponse{}
	mi := &file_shredstream_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShredstreamHeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShredstreamHeartbeatResponse) ProtoMessage() {}

func (x *ShredstreamHeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shredstream_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShredstreamHeartbeatResponse.ProtoReflect.Descriptor instead.
func (*ShredstreamHeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_shredstream_proto_rawDescGZIP(), []int{2}
}

func (x *ShredstreamHeartbeatResponse) GetTtlMs() uint32 {
	if x != nil {
		return x.TtlMs
	}
	return 0
}

type TraceShred struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// source region, one of: https://docs.jito.wtf/lowlatencytxnsend/#api
	Region string `protobuf:"bytes,1,opt,name=region,proto3" json:"region,omitempty"`
	// timestamp of creation
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// monotonically increases, resets upon service restart
	SeqNum        uint32 `protobuf:"varint,3,opt,name=seq_num,json=seqNum,proto3" json:"seq_num,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TraceShred) Reset() {
	*x = TraceShred{}
	mi := &file_shredstream_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TraceShred) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TraceShred) ProtoMessage() {}

func (x *TraceShred) ProtoReflect() protoreflect.Message {
	mi := &file_shredstream_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TraceShred.ProtoReflect.Descriptor instead.
func (*TraceShred) Descriptor() ([]byte, []int) {
	return file_shredstream_proto_rawDescGZIP(), []int{3}
}

func (x *TraceShred) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *TraceShred) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *TraceShred) GetSeqNum() uint32 {
	if x != nil {
		return x.SeqNum
	}
	return 0
}

type SubscribeEntriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeEntriesRequest) Reset() {
	*x = SubscribeEntriesRequest{}
	mi := &file_shredstream_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeEntriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeEntriesRequest) ProtoMessage() {}

func (x *SubscribeEntriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shredstream_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeEntriesRequest.ProtoReflect.Descriptor instead.
func (*SubscribeEntriesRequest) Descriptor() ([]byte, []int) {
	return file_shredstream_proto_rawDescGZIP(), []int{4}
}

type Entry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// the slot that the entry is from
	Slot uint64 `protobuf:"varint,1,opt,name=slot,proto3" json:"slot,omitempty"`
	// Serialized bytes of Vec<Entry>: https://docs.rs/solana-entry/latest/solana_entry/entry/struct.Entry.html
	Entries       []byte `protobuf:"bytes,2,opt,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Entry) Reset() {
	*x = Entry{}
	mi := &file_shredstream_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entry) ProtoMessage() {}

func (x *Entry) ProtoReflect() protoreflect.Message {
	mi := &file_shredstream_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entry.ProtoReflect.Descriptor instead.
func (*Entry) Descriptor() ([]byte, []int) {
	return file_shredstream_proto_rawDescGZIP(), []int{5}
}

func (x *Entry) GetSlot() uint64 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *Entry) GetEntries() []byte {
	if x != nil {
		return x.Entries
	}
	return nil
}

var File_shredstream_proto protoreflect.FileDescriptor

const file_shredstream_proto_rawDesc = "" +
	"\n" +
	"\x11shredstream.proto\x12\vshredstream\x1a\x1fgoogle/protobuf/timestamp.proto\"7\n" +
	"\x11ShredstreamSocket\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\x12\x12\n" +
	"\x04port\x18\x02 \x01(\x03R\x04port\"h\n" +
	"\x14ShredstreamHeartbeat\x126\n" +
	"\x06socket\x18\x01 \x01(\v2\x1e.shredstream.ShredstreamSocketR\x06socket\x12\x18\n" +
	"\aregions\x18\x02 \x03(\tR\aregions\"5\n" +
	"\x1cShredstreamHeartbeatResponse\x12\x15\n" +
	"\x06ttl_ms\x18\x01 \x01(\rR\x05ttlMs\"x\n" +
	"\n" +
	"TraceShred\x12\x16\n" +
	"\x06region\x18\x01 \x01(\tR\x06region\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x17\n" +
	"\aseq_num\x18\x03 \x01(\rR\x06seqNum\"\x19\n" +
	"\x17SubscribeEntriesRequest\"5\n" +
	"\x05Entry\x12\x12\n" +
	"\x04slot\x18\x01 \x01(\x04R\x04slot\x12\x18\n" +
	"\aentries\x18\x02 \x01(\fR\aentries2n\n" +
	"\vShredstream\x12_\n" +
	"\rSendHeartbeat\x12!.shredstream.ShredstreamHeartbeat\x1a).shredstream.ShredstreamHeartbeatResponse\"\x002b\n" +
	"\x10ShredstreamProxy\x12N\n" +
	"\x10SubscribeEntries\x12$.shredstream.SubscribeEntriesRequest\x1a\x12.shredstream.Entry0\x01B*Z(github.com/iqbalbaharum/solana-protos/pbb\x06proto3"

var (
	file_shredstream_proto_rawDescOnce sync.Once
	file_shredstream_proto_rawDescData []byte
)

func file_shredstream_proto_rawDescGZIP() []byte {
	file_shredstream_proto_rawDescOnce.Do(func() {
		file_shredstream_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shredstream_proto_rawDesc), len(file_shredstream_proto_rawDesc)))
	})
	return file_shredstream_proto_rawDescData
}

var file_shredstream_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_shredstream_proto_goTypes = []any{
	(*ShredstreamSocket)(nil),            // 0: shredstream.ShredstreamSocket
	(*ShredstreamHeartbeat)(nil),         // 1: shredstream.ShredstreamHeartbeat
	(*ShredstreamHeartbeatResponse)(nil), // 2: shredstream.ShredstreamHeartbeatResponse
	(*TraceShred)(nil),                   // 3: shredstream.TraceShred
	(*SubscribeEntriesRequest)(nil),      // 4: shredstream.SubscribeEntriesRequest
	(*Entry)(nil),                        // 5: shredstream.Entry
	(*timestamppb.Timestamp)(nil),        // 6: google.protobuf.Timestamp
}
var file_shredstream_proto_depIdxs = []int32{
	0, // 0: shredstream.ShredstreamHeartbeat.socket:type_name -> shredstream.ShredstreamSocket
	6, // 1: shredstream.TraceShred.created_at:type_name -> google.protobuf.Timestamp
	1, // 2: shredstream.Shredstream.SendHeartbeat:input_type -> shredstream.ShredstreamHeartbeat
	4, // 3: shredstream.ShredstreamProxy.SubscribeEntries:input_type -> shredstream.SubscribeEntriesRequest
	2, // 4: shredstream.Shredstream.SendHeartbeat:output_type -> shredstream.ShredstreamHeartbeatResponse
	5, // 5: shredstream.ShredstreamProxy.SubscribeEntries:output_type -> shredstream.Entry
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_shredstream_proto_init() }
func file_shredstream_proto_init() {
	if File_shredstream_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shredstream_proto_rawDesc), len(file_shredstream_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_shredstream_proto_goTypes,
		DependencyIndexes: file_shredstream_proto_depIdxs,
		MessageInfos:      file_shredstream_proto_msgTypes,
	}.Build()
	File_shredstream_proto = out.File
	file_shredstream_proto_goTypes = nil
	file_shredstream_proto_depIdxs = nil
}
