// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.27.3
// source: solana-storage.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GeyserRewardType int32

const (
	GeyserRewardType_Unspecified GeyserRewardType = 0
	GeyserRewardType_Fee         GeyserRewardType = 1
	GeyserRewardType_Rent        GeyserRewardType = 2
	GeyserRewardType_Staking     GeyserRewardType = 3
	GeyserRewardType_Voting      GeyserRewardType = 4
)

// Enum value maps for GeyserRewardType.
var (
	GeyserRewardType_name = map[int32]string{
		0: "Unspecified",
		1: "Fee",
		2: "Rent",
		3: "Staking",
		4: "Voting",
	}
	GeyserRewardType_value = map[string]int32{
		"Unspecified": 0,
		"Fee":         1,
		"Rent":        2,
		"Staking":     3,
		"Voting":      4,
	}
)

func (x GeyserRewardType) Enum() *GeyserRewardType {
	p := new(GeyserRewardType)
	*p = x
	return p
}

func (x GeyserRewardType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GeyserRewardType) Descriptor() protoreflect.EnumDescriptor {
	return file_solana_storage_proto_enumTypes[0].Descriptor()
}

func (GeyserRewardType) Type() protoreflect.EnumType {
	return &file_solana_storage_proto_enumTypes[0]
}

func (x GeyserRewardType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GeyserRewardType.Descriptor instead.
func (GeyserRewardType) EnumDescriptor() ([]byte, []int) {
	return file_solana_storage_proto_rawDescGZIP(), []int{0}
}

type GeyserConfirmedBlock struct {
	state             protoimpl.MessageState  `protogen:"open.v1"`
	PreviousBlockhash string                  `protobuf:"bytes,1,opt,name=previous_blockhash,json=previousBlockhash,proto3" json:"previous_blockhash,omitempty"`
	Blockhash         string                  `protobuf:"bytes,2,opt,name=blockhash,proto3" json:"blockhash,omitempty"`
	ParentSlot        uint64                  `protobuf:"varint,3,opt,name=parent_slot,json=parentSlot,proto3" json:"parent_slot,omitempty"`
	Transactions      []*ConfirmedTransaction `protobuf:"bytes,4,rep,name=transactions,proto3" json:"transactions,omitempty"`
	Rewards           []*GeyserReward         `protobuf:"bytes,5,rep,name=rewards,proto3" json:"rewards,omitempty"`
	BlockTime         *UnixTimestamp          `protobuf:"bytes,6,opt,name=block_time,json=blockTime,proto3" json:"block_time,omitempty"`
	BlockHeight       *BlockHeight            `protobuf:"bytes,7,opt,name=block_height,json=blockHeight,proto3" json:"block_height,omitempty"`
	NumPartitions     *NumPartitions          `protobuf:"bytes,8,opt,name=num_partitions,json=numPartitions,proto3" json:"num_partitions,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GeyserConfirmedBlock) Reset() {
	*x = GeyserConfirmedBlock{}
	mi := &file_solana_storage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeyserConfirmedBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeyserConfirmedBlock) ProtoMessage() {}

func (x *GeyserConfirmedBlock) ProtoReflect() protoreflect.Message {
	mi := &file_solana_storage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeyserConfirmedBlock.ProtoReflect.Descriptor instead.
func (*GeyserConfirmedBlock) Descriptor() ([]byte, []int) {
	return file_solana_storage_proto_rawDescGZIP(), []int{0}
}

func (x *GeyserConfirmedBlock) GetPreviousBlockhash() string {
	if x != nil {
		return x.PreviousBlockhash
	}
	return ""
}

func (x *GeyserConfirmedBlock) GetBlockhash() string {
	if x != nil {
		return x.Blockhash
	}
	return ""
}

func (x *GeyserConfirmedBlock) GetParentSlot() uint64 {
	if x != nil {
		return x.ParentSlot
	}
	return 0
}

func (x *GeyserConfirmedBlock) GetTransactions() []*ConfirmedTransaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

func (x *GeyserConfirmedBlock) GetRewards() []*GeyserReward {
	if x != nil {
		return x.Rewards
	}
	return nil
}

func (x *GeyserConfirmedBlock) GetBlockTime() *UnixTimestamp {
	if x != nil {
		return x.BlockTime
	}
	return nil
}

func (x *GeyserConfirmedBlock) GetBlockHeight() *BlockHeight {
	if x != nil {
		return x.BlockHeight
	}
	return nil
}

func (x *GeyserConfirmedBlock) GetNumPartitions() *NumPartitions {
	if x != nil {
		return x.NumPartitions
	}
	return nil
}

type ConfirmedTransaction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transaction   *Transaction           `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
	Meta          *TransactionStatusMeta `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmedTransaction) Reset() {
	*x = ConfirmedTransaction{}
	mi := &file_solana_storage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmedTransaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmedTransaction) ProtoMessage() {}

func (x *ConfirmedTransaction) ProtoReflect() protoreflect.Message {
	mi := &file_solana_storage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmedTransaction.ProtoReflect.Descriptor instead.
func (*ConfirmedTransaction) Descriptor() ([]byte, []int) {
	return file_solana_storage_proto_rawDescGZIP(), []int{1}
}

func (x *ConfirmedTransaction) GetTransaction() *Transaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

func (x *ConfirmedTransaction) GetMeta() *TransactionStatusMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

type Transaction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Signatures    [][]byte               `protobuf:"bytes,1,rep,name=signatures,proto3" json:"signatures,omitempty"`
	Message       *Message               `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_solana_storage_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_solana_storage_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_solana_storage_proto_rawDescGZIP(), []int{2}
}

func (x *Transaction) GetSignatures() [][]byte {
	if x != nil {
		return x.Signatures
	}
	return nil
}

func (x *Transaction) GetMessage() *Message {
	if x != nil {
		return x.Message
	}
	return nil
}

type Message struct {
	state               protoimpl.MessageState       `protogen:"open.v1"`
	Header              *MessageHeader               `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	AccountKeys         [][]byte                     `protobuf:"bytes,2,rep,name=account_keys,json=accountKeys,proto3" json:"account_keys,omitempty"`
	RecentBlockhash     []byte                       `protobuf:"bytes,3,opt,name=recent_blockhash,json=recentBlockhash,proto3" json:"recent_blockhash,omitempty"`
	Instructions        []*CompiledInstruction       `protobuf:"bytes,4,rep,name=instructions,proto3" json:"instructions,omitempty"`
	Versioned           bool                         `protobuf:"varint,5,opt,name=versioned,proto3" json:"versioned,omitempty"`
	AddressTableLookups []*MessageAddressTableLookup `protobuf:"bytes,6,rep,name=address_table_lookups,json=addressTableLookups,proto3" json:"address_table_lookups,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_solana_storage_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_solana_storage_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_solana_storage_proto_rawDescGZIP(), []int{3}
}

func (x *Message) GetHeader() *MessageHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *Message) GetAccountKeys() [][]byte {
	if x != nil {
		return x.AccountKeys
	}
	return nil
}

func (x *Message) GetRecentBlockhash() []byte {
	if x != nil {
		return x.RecentBlockhash
	}
	return nil
}

func (x *Message) GetInstructions() []*CompiledInstruction {
	if x != nil {
		return x.Instructions
	}
	return nil
}

func (x *Message) GetVersioned() bool {
	if x != nil {
		return x.Versioned
	}
	return false
}

func (x *Message) GetAddressTableLookups() []*MessageAddressTableLookup {
	if x != nil {
		return x.AddressTableLookups
	}
	return nil
}

type MessageHeader struct {
	state                       protoimpl.MessageState `protogen:"open.v1"`
	NumRequiredSignatures       uint32                 `protobuf:"varint,1,opt,name=num_required_signatures,json=numRequiredSignatures,proto3" json:"num_required_signatures,omitempty"`
	NumReadonlySignedAccounts   uint32                 `protobuf:"varint,2,opt,name=num_readonly_signed_accounts,json=numReadonlySignedAccounts,proto3" json:"num_readonly_signed_accounts,omitempty"`
	NumReadonlyUnsignedAccounts uint32                 `protobuf:"varint,3,opt,name=num_readonly_unsigned_accounts,json=numReadonlyUnsignedAccounts,proto3" json:"num_readonly_unsigned_accounts,omitempty"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *MessageHeader) Reset() {
	*x = MessageHeader{}
	mi := &file_solana_storage_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageHeader) ProtoMessage() {}

func (x *MessageHeader) ProtoReflect() protoreflect.Message {
	mi := &file_solana_storage_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageHeader.ProtoReflect.Descriptor instead.
func (*MessageHeader) Descriptor() ([]byte, []int) {
	return file_solana_storage_proto_rawDescGZIP(), []int{4}
}

func (x *MessageHeader) GetNumRequiredSignatures() uint32 {
	if x != nil {
		return x.NumRequiredSignatures
	}
	return 0
}

func (x *MessageHeader) GetNumReadonlySignedAccounts() uint32 {
	if x != nil {
		return x.NumReadonlySignedAccounts
	}
	return 0
}

func (x *MessageHeader) GetNumReadonlyUnsignedAccounts() uint32 {
	if x != nil {
		return x.NumReadonlyUnsignedAccounts
	}
	return 0
}

type MessageAddressTableLookup struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AccountKey      []byte                 `protobuf:"bytes,1,opt,name=account_key,json=accountKey,proto3" json:"account_key,omitempty"`
	WritableIndexes []byte                 `protobuf:"bytes,2,opt,name=writable_indexes,json=writableIndexes,proto3" json:"writable_indexes,omitempty"`
	ReadonlyIndexes []byte                 `protobuf:"bytes,3,opt,name=readonly_indexes,json=readonlyIndexes,proto3" json:"readonly_indexes,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MessageAddressTableLookup) Reset() {
	*x = MessageAddressTableLookup{}
	mi := &file_solana_storage_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageAddressTableLookup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageAddressTableLookup) ProtoMessage() {}

func (x *MessageAddressTableLookup) ProtoReflect() protoreflect.Message {
	mi := &file_solana_storage_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageAddressTableLookup.ProtoReflect.Descriptor instead.
func (*MessageAddressTableLookup) Descriptor() ([]byte, []int) {
	return file_solana_storage_proto_rawDescGZIP(), []int{5}
}

func (x *MessageAddressTableLookup) GetAccountKey() []byte {
	if x != nil {
		return x.AccountKey
	}
	return nil
}

func (x *MessageAddressTableLookup) GetWritableIndexes() []byte {
	if x != nil {
		return x.WritableIndexes
	}
	return nil
}

func (x *MessageAddressTableLookup) GetReadonlyIndexes() []byte {
	if x != nil {
		return x.ReadonlyIndexes
	}
	return nil
}

type TransactionStatusMeta struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	Err                     *TransactionError      `protobuf:"bytes,1,opt,name=err,proto3" json:"err,omitempty"`
	Fee                     uint64                 `protobuf:"varint,2,opt,name=fee,proto3" json:"fee,omitempty"`
	PreBalances             []uint64               `protobuf:"varint,3,rep,packed,name=pre_balances,json=preBalances,proto3" json:"pre_balances,omitempty"`
	PostBalances            []uint64               `protobuf:"varint,4,rep,packed,name=post_balances,json=postBalances,proto3" json:"post_balances,omitempty"`
	InnerInstructions       []*InnerInstructions   `protobuf:"bytes,5,rep,name=inner_instructions,json=innerInstructions,proto3" json:"inner_instructions,omitempty"`
	InnerInstructionsNone   bool                   `protobuf:"varint,10,opt,name=inner_instructions_none,json=innerInstructionsNone,proto3" json:"inner_instructions_none,omitempty"`
	LogMessages             []string               `protobuf:"bytes,6,rep,name=log_messages,json=logMessages,proto3" json:"log_messages,omitempty"`
	LogMessagesNone         bool                   `protobuf:"varint,11,opt,name=log_messages_none,json=logMessagesNone,proto3" json:"log_messages_none,omitempty"`
	PreTokenBalances        []*TokenBalance        `protobuf:"bytes,7,rep,name=pre_token_balances,json=preTokenBalances,proto3" json:"pre_token_balances,omitempty"`
	PostTokenBalances       []*TokenBalance        `protobuf:"bytes,8,rep,name=post_token_balances,json=postTokenBalances,proto3" json:"post_token_balances,omitempty"`
	Rewards                 []*GeyserReward        `protobuf:"bytes,9,rep,name=rewards,proto3" json:"rewards,omitempty"`
	LoadedWritableAddresses [][]byte               `protobuf:"bytes,12,rep,name=loaded_writable_addresses,json=loadedWritableAddresses,proto3" json:"loaded_writable_addresses,omitempty"`
	LoadedReadonlyAddresses [][]byte               `protobuf:"bytes,13,rep,name=loaded_readonly_addresses,json=loadedReadonlyAddresses,proto3" json:"loaded_readonly_addresses,omitempty"`
	ReturnData              *ReturnData            `protobuf:"bytes,14,opt,name=return_data,json=returnData,proto3" json:"return_data,omitempty"`
	ReturnDataNone          bool                   `protobuf:"varint,15,opt,name=return_data_none,json=returnDataNone,proto3" json:"return_data_none,omitempty"`
	// Sum of compute units consumed by all instructions.
	// Available since Solana v1.10.35 / v1.11.6.
	// Set to `None` for txs executed on earlier versions.
	ComputeUnitsConsumed *uint64 `protobuf:"varint,16,opt,name=compute_units_consumed,json=computeUnitsConsumed,proto3,oneof" json:"compute_units_consumed,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *TransactionStatusMeta) Reset() {
	*x = TransactionStatusMeta{}
	mi := &file_solana_storage_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionStatusMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionStatusMeta) ProtoMessage() {}

func (x *TransactionStatusMeta) ProtoReflect() protoreflect.Message {
	mi := &file_solana_storage_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionStatusMeta.ProtoReflect.Descriptor instead.
func (*TransactionStatusMeta) Descriptor() ([]byte, []int) {
	return file_solana_storage_proto_rawDescGZIP(), []int{6}
}

func (x *TransactionStatusMeta) GetErr() *TransactionError {
	if x != nil {
		return x.Err
	}
	return nil
}

func (x *TransactionStatusMeta) GetFee() uint64 {
	if x != nil {
		return x.Fee
	}
	return 0
}

func (x *TransactionStatusMeta) GetPreBalances() []uint64 {
	if x != nil {
		return x.PreBalances
	}
	return nil
}

func (x *TransactionStatusMeta) GetPostBalances() []uint64 {
	if x != nil {
		return x.PostBalances
	}
	return nil
}

func (x *TransactionStatusMeta) GetInnerInstructions() []*InnerInstructions {
	if x != nil {
		return x.InnerInstructions
	}
	return nil
}

func (x *TransactionStatusMeta) GetInnerInstructionsNone() bool {
	if x != nil {
		return x.InnerInstructionsNone
	}
	return false
}

func (x *TransactionStatusMeta) GetLogMessages() []string {
	if x != nil {
		return x.LogMessages
	}
	return nil
}

func (x *TransactionStatusMeta) GetLogMessagesNone() bool {
	if x != nil {
		return x.LogMessagesNone
	}
	return false
}

func (x *TransactionStatusMeta) GetPreTokenBalances() []*TokenBalance {
	if x != nil {
		return x.PreTokenBalances
	}
	return nil
}

func (x *TransactionStatusMeta) GetPostTokenBalances() []*TokenBalance {
	if x != nil {
		return x.PostTokenBalances
	}
	return nil
}

func (x *TransactionStatusMeta) GetRewards() []*GeyserReward {
	if x != nil {
		return x.Rewards
	}
	return nil
}

func (x *TransactionStatusMeta) GetLoadedWritableAddresses() [][]byte {
	if x != nil {
		return x.LoadedWritableAddresses
	}
	return nil
}

func (x *TransactionStatusMeta) GetLoadedReadonlyAddresses() [][]byte {
	if x != nil {
		return x.LoadedReadonlyAddresses
	}
	return nil
}

func (x *TransactionStatusMeta) GetReturnData() *ReturnData {
	if x != nil {
		return x.ReturnData
	}
	return nil
}

func (x *TransactionStatusMeta) GetReturnDataNone() bool {
	if x != nil {
		return x.ReturnDataNone
	}
	return false
}

func (x *TransactionStatusMeta) GetComputeUnitsConsumed() uint64 {
	if x != nil && x.ComputeUnitsConsumed != nil {
		return *x.ComputeUnitsConsumed
	}
	return 0
}

type TransactionError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Err           []byte                 `protobuf:"bytes,1,opt,name=err,proto3" json:"err,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionError) Reset() {
	*x = TransactionError{}
	mi := &file_solana_storage_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionError) ProtoMessage() {}

func (x *TransactionError) ProtoReflect() protoreflect.Message {
	mi := &file_solana_storage_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionError.ProtoReflect.Descriptor instead.
func (*TransactionError) Descriptor() ([]byte, []int) {
	return file_solana_storage_proto_rawDescGZIP(), []int{7}
}

func (x *TransactionError) GetErr() []byte {
	if x != nil {
		return x.Err
	}
	return nil
}

type InnerInstructions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         uint32                 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Instructions  []*InnerInstruction    `protobuf:"bytes,2,rep,name=instructions,proto3" json:"instructions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InnerInstructions) Reset() {
	*x = InnerInstructions{}
	mi := &file_solana_storage_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InnerInstructions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InnerInstructions) ProtoMessage() {}

func (x *InnerInstructions) ProtoReflect() protoreflect.Message {
	mi := &file_solana_storage_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InnerInstructions.ProtoReflect.Descriptor instead.
func (*InnerInstructions) Descriptor() ([]byte, []int) {
	return file_solana_storage_proto_rawDescGZIP(), []int{8}
}

func (x *InnerInstructions) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *InnerInstructions) GetInstructions() []*InnerInstruction {
	if x != nil {
		return x.Instructions
	}
	return nil
}

type InnerInstruction struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ProgramIdIndex uint32                 `protobuf:"varint,1,opt,name=program_id_index,json=programIdIndex,proto3" json:"program_id_index,omitempty"`
	Accounts       []byte                 `protobuf:"bytes,2,opt,name=accounts,proto3" json:"accounts,omitempty"`
	Data           []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	// Invocation stack height of an inner instruction.
	// Available since Solana v1.14.6
	// Set to `None` for txs executed on earlier versions.
	StackHeight   *uint32 `protobuf:"varint,4,opt,name=stack_height,json=stackHeight,proto3,oneof" json:"stack_height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InnerInstruction) Reset() {
	*x = InnerInstruction{}
	mi := &file_solana_storage_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InnerInstruction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InnerInstruction) ProtoMessage() {}

func (x *InnerInstruction) ProtoReflect() protoreflect.Message {
	mi := &file_solana_storage_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InnerInstruction.ProtoReflect.Descriptor instead.
func (*InnerInstruction) Descriptor() ([]byte, []int) {
	return file_solana_storage_proto_rawDescGZIP(), []int{9}
}

func (x *InnerInstruction) GetProgramIdIndex() uint32 {
	if x != nil {
		return x.ProgramIdIndex
	}
	return 0
}

func (x *InnerInstruction) GetAccounts() []byte {
	if x != nil {
		return x.Accounts
	}
	return nil
}

func (x *InnerInstruction) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *InnerInstruction) GetStackHeight() uint32 {
	if x != nil && x.StackHeight != nil {
		return *x.StackHeight
	}
	return 0
}

type CompiledInstruction struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ProgramIdIndex uint32                 `protobuf:"varint,1,opt,name=program_id_index,json=programIdIndex,proto3" json:"program_id_index,omitempty"`
	Accounts       []byte                 `protobuf:"bytes,2,opt,name=accounts,proto3" json:"accounts,omitempty"`
	Data           []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CompiledInstruction) Reset() {
	*x = CompiledInstruction{}
	mi := &file_solana_storage_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompiledInstruction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompiledInstruction) ProtoMessage() {}

func (x *CompiledInstruction) ProtoReflect() protoreflect.Message {
	mi := &file_solana_storage_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompiledInstruction.ProtoReflect.Descriptor instead.
func (*CompiledInstruction) Descriptor() ([]byte, []int) {
	return file_solana_storage_proto_rawDescGZIP(), []int{10}
}

func (x *CompiledInstruction) GetProgramIdIndex() uint32 {
	if x != nil {
		return x.ProgramIdIndex
	}
	return 0
}

func (x *CompiledInstruction) GetAccounts() []byte {
	if x != nil {
		return x.Accounts
	}
	return nil
}

func (x *CompiledInstruction) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type TokenBalance struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountIndex  uint32                 `protobuf:"varint,1,opt,name=account_index,json=accountIndex,proto3" json:"account_index,omitempty"`
	Mint          string                 `protobuf:"bytes,2,opt,name=mint,proto3" json:"mint,omitempty"`
	UiTokenAmount *UiTokenAmount         `protobuf:"bytes,3,opt,name=ui_token_amount,json=uiTokenAmount,proto3" json:"ui_token_amount,omitempty"`
	Owner         string                 `protobuf:"bytes,4,opt,name=owner,proto3" json:"owner,omitempty"`
	ProgramId     string                 `protobuf:"bytes,5,opt,name=program_id,json=programId,proto3" json:"program_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenBalance) Reset() {
	*x = TokenBalance{}
	mi := &file_solana_storage_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenBalance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenBalance) ProtoMessage() {}

func (x *TokenBalance) ProtoReflect() protoreflect.Message {
	mi := &file_solana_storage_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenBalance.ProtoReflect.Descriptor instead.
func (*TokenBalance) Descriptor() ([]byte, []int) {
	return file_solana_storage_proto_rawDescGZIP(), []int{11}
}

func (x *TokenBalance) GetAccountIndex() uint32 {
	if x != nil {
		return x.AccountIndex
	}
	return 0
}

func (x *TokenBalance) GetMint() string {
	if x != nil {
		return x.Mint
	}
	return ""
}

func (x *TokenBalance) GetUiTokenAmount() *UiTokenAmount {
	if x != nil {
		return x.UiTokenAmount
	}
	return nil
}

func (x *TokenBalance) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *TokenBalance) GetProgramId() string {
	if x != nil {
		return x.ProgramId
	}
	return ""
}

type UiTokenAmount struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UiAmount       float64                `protobuf:"fixed64,1,opt,name=ui_amount,json=uiAmount,proto3" json:"ui_amount,omitempty"`
	Decimals       uint32                 `protobuf:"varint,2,opt,name=decimals,proto3" json:"decimals,omitempty"`
	Amount         string                 `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
	UiAmountString string                 `protobuf:"bytes,4,opt,name=ui_amount_string,json=uiAmountString,proto3" json:"ui_amount_string,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UiTokenAmount) Reset() {
	*x = UiTokenAmount{}
	mi := &file_solana_storage_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UiTokenAmount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UiTokenAmount) ProtoMessage() {}

func (x *UiTokenAmount) ProtoReflect() protoreflect.Message {
	mi := &file_solana_storage_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UiTokenAmount.ProtoReflect.Descriptor instead.
func (*UiTokenAmount) Descriptor() ([]byte, []int) {
	return file_solana_storage_proto_rawDescGZIP(), []int{12}
}

func (x *UiTokenAmount) GetUiAmount() float64 {
	if x != nil {
		return x.UiAmount
	}
	return 0
}

func (x *UiTokenAmount) GetDecimals() uint32 {
	if x != nil {
		return x.Decimals
	}
	return 0
}

func (x *UiTokenAmount) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *UiTokenAmount) GetUiAmountString() string {
	if x != nil {
		return x.UiAmountString
	}
	return ""
}

type ReturnData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProgramId     []byte                 `protobuf:"bytes,1,opt,name=program_id,json=programId,proto3" json:"program_id,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReturnData) Reset() {
	*x = ReturnData{}
	mi := &file_solana_storage_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReturnData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReturnData) ProtoMessage() {}

func (x *ReturnData) ProtoReflect() protoreflect.Message {
	mi := &file_solana_storage_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReturnData.ProtoReflect.Descriptor instead.
func (*ReturnData) Descriptor() ([]byte, []int) {
	return file_solana_storage_proto_rawDescGZIP(), []int{13}
}

func (x *ReturnData) GetProgramId() []byte {
	if x != nil {
		return x.ProgramId
	}
	return nil
}

func (x *ReturnData) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type GeyserReward struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pubkey        string                 `protobuf:"bytes,1,opt,name=pubkey,proto3" json:"pubkey,omitempty"`
	Lamports      int64                  `protobuf:"varint,2,opt,name=lamports,proto3" json:"lamports,omitempty"`
	PostBalance   uint64                 `protobuf:"varint,3,opt,name=post_balance,json=postBalance,proto3" json:"post_balance,omitempty"`
	RewardType    GeyserRewardType       `protobuf:"varint,4,opt,name=reward_type,json=rewardType,proto3,enum=solana.storage.GeyserConfirmedBlock.GeyserRewardType" json:"reward_type,omitempty"`
	Commission    string                 `protobuf:"bytes,5,opt,name=commission,proto3" json:"commission,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeyserReward) Reset() {
	*x = GeyserReward{}
	mi := &file_solana_storage_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeyserReward) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeyserReward) ProtoMessage() {}

func (x *GeyserReward) ProtoReflect() protoreflect.Message {
	mi := &file_solana_storage_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeyserReward.ProtoReflect.Descriptor instead.
func (*GeyserReward) Descriptor() ([]byte, []int) {
	return file_solana_storage_proto_rawDescGZIP(), []int{14}
}

func (x *GeyserReward) GetPubkey() string {
	if x != nil {
		return x.Pubkey
	}
	return ""
}

func (x *GeyserReward) GetLamports() int64 {
	if x != nil {
		return x.Lamports
	}
	return 0
}

func (x *GeyserReward) GetPostBalance() uint64 {
	if x != nil {
		return x.PostBalance
	}
	return 0
}

func (x *GeyserReward) GetRewardType() GeyserRewardType {
	if x != nil {
		return x.RewardType
	}
	return GeyserRewardType_Unspecified
}

func (x *GeyserReward) GetCommission() string {
	if x != nil {
		return x.Commission
	}
	return ""
}

type GeyserRewards struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rewards       []*GeyserReward        `protobuf:"bytes,1,rep,name=rewards,proto3" json:"rewards,omitempty"`
	NumPartitions *NumPartitions         `protobuf:"bytes,2,opt,name=num_partitions,json=numPartitions,proto3" json:"num_partitions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeyserRewards) Reset() {
	*x = GeyserRewards{}
	mi := &file_solana_storage_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeyserRewards) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeyserRewards) ProtoMessage() {}

func (x *GeyserRewards) ProtoReflect() protoreflect.Message {
	mi := &file_solana_storage_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeyserRewards.ProtoReflect.Descriptor instead.
func (*GeyserRewards) Descriptor() ([]byte, []int) {
	return file_solana_storage_proto_rawDescGZIP(), []int{15}
}

func (x *GeyserRewards) GetRewards() []*GeyserReward {
	if x != nil {
		return x.Rewards
	}
	return nil
}

func (x *GeyserRewards) GetNumPartitions() *NumPartitions {
	if x != nil {
		return x.NumPartitions
	}
	return nil
}

type UnixTimestamp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnixTimestamp) Reset() {
	*x = UnixTimestamp{}
	mi := &file_solana_storage_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnixTimestamp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnixTimestamp) ProtoMessage() {}

func (x *UnixTimestamp) ProtoReflect() protoreflect.Message {
	mi := &file_solana_storage_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnixTimestamp.ProtoReflect.Descriptor instead.
func (*UnixTimestamp) Descriptor() ([]byte, []int) {
	return file_solana_storage_proto_rawDescGZIP(), []int{16}
}

func (x *UnixTimestamp) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type BlockHeight struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlockHeight   uint64                 `protobuf:"varint,1,opt,name=block_height,json=blockHeight,proto3" json:"block_height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockHeight) Reset() {
	*x = BlockHeight{}
	mi := &file_solana_storage_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockHeight) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockHeight) ProtoMessage() {}

func (x *BlockHeight) ProtoReflect() protoreflect.Message {
	mi := &file_solana_storage_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockHeight.ProtoReflect.Descriptor instead.
func (*BlockHeight) Descriptor() ([]byte, []int) {
	return file_solana_storage_proto_rawDescGZIP(), []int{17}
}

func (x *BlockHeight) GetBlockHeight() uint64 {
	if x != nil {
		return x.BlockHeight
	}
	return 0
}

type NumPartitions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NumPartitions uint64                 `protobuf:"varint,1,opt,name=num_partitions,json=numPartitions,proto3" json:"num_partitions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NumPartitions) Reset() {
	*x = NumPartitions{}
	mi := &file_solana_storage_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NumPartitions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NumPartitions) ProtoMessage() {}

func (x *NumPartitions) ProtoReflect() protoreflect.Message {
	mi := &file_solana_storage_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NumPartitions.ProtoReflect.Descriptor instead.
func (*NumPartitions) Descriptor() ([]byte, []int) {
	return file_solana_storage_proto_rawDescGZIP(), []int{18}
}

func (x *NumPartitions) GetNumPartitions() uint64 {
	if x != nil {
		return x.NumPartitions
	}
	return 0
}

var File_solana_storage_proto protoreflect.FileDescriptor

const file_solana_storage_proto_rawDesc = "" +
	"\n" +
	"\x14solana-storage.proto\x12#solana.storage.GeyserConfirmedBlock\"\xb3\x04\n" +
	"\x14GeyserConfirmedBlock\x12-\n" +
	"\x12previous_blockhash\x18\x01 \x01(\tR\x11previousBlockhash\x12\x1c\n" +
	"\tblockhash\x18\x02 \x01(\tR\tblockhash\x12\x1f\n" +
	"\vparent_slot\x18\x03 \x01(\x04R\n" +
	"parentSlot\x12]\n" +
	"\ftransactions\x18\x04 \x03(\v29.solana.storage.GeyserConfirmedBlock.ConfirmedTransactionR\ftransactions\x12K\n" +
	"\arewards\x18\x05 \x03(\v21.solana.storage.GeyserConfirmedBlock.GeyserRewardR\arewards\x12Q\n" +
	"\n" +
	"block_time\x18\x06 \x01(\v22.solana.storage.GeyserConfirmedBlock.UnixTimestampR\tblockTime\x12S\n" +
	"\fblock_height\x18\a \x01(\v20.solana.storage.GeyserConfirmedBlock.BlockHeightR\vblockHeight\x12Y\n" +
	"\x0enum_partitions\x18\b \x01(\v22.solana.storage.GeyserConfirmedBlock.NumPartitionsR\rnumPartitions\"\xba\x01\n" +
	"\x14ConfirmedTransaction\x12R\n" +
	"\vtransaction\x18\x01 \x01(\v20.solana.storage.GeyserConfirmedBlock.TransactionR\vtransaction\x12N\n" +
	"\x04meta\x18\x02 \x01(\v2:.solana.storage.GeyserConfirmedBlock.TransactionStatusMetaR\x04meta\"u\n" +
	"\vTransaction\x12\x1e\n" +
	"\n" +
	"signatures\x18\x01 \x03(\fR\n" +
	"signatures\x12F\n" +
	"\amessage\x18\x02 \x01(\v2,.solana.storage.GeyserConfirmedBlock.MessageR\amessage\"\x93\x03\n" +
	"\aMessage\x12J\n" +
	"\x06header\x18\x01 \x01(\v22.solana.storage.GeyserConfirmedBlock.MessageHeaderR\x06header\x12!\n" +
	"\faccount_keys\x18\x02 \x03(\fR\vaccountKeys\x12)\n" +
	"\x10recent_blockhash\x18\x03 \x01(\fR\x0frecentBlockhash\x12\\\n" +
	"\finstructions\x18\x04 \x03(\v28.solana.storage.GeyserConfirmedBlock.CompiledInstructionR\finstructions\x12\x1c\n" +
	"\tversioned\x18\x05 \x01(\bR\tversioned\x12r\n" +
	"\x15address_table_lookups\x18\x06 \x03(\v2>.solana.storage.GeyserConfirmedBlock.MessageAddressTableLookupR\x13addressTableLookups\"\xcd\x01\n" +
	"\rMessageHeader\x126\n" +
	"\x17num_required_signatures\x18\x01 \x01(\rR\x15numRequiredSignatures\x12?\n" +
	"\x1cnum_readonly_signed_accounts\x18\x02 \x01(\rR\x19numReadonlySignedAccounts\x12C\n" +
	"\x1enum_readonly_unsigned_accounts\x18\x03 \x01(\rR\x1bnumReadonlyUnsignedAccounts\"\x92\x01\n" +
	"\x19MessageAddressTableLookup\x12\x1f\n" +
	"\vaccount_key\x18\x01 \x01(\fR\n" +
	"accountKey\x12)\n" +
	"\x10writable_indexes\x18\x02 \x01(\fR\x0fwritableIndexes\x12)\n" +
	"\x10readonly_indexes\x18\x03 \x01(\fR\x0freadonlyIndexes\"\x83\b\n" +
	"\x15TransactionStatusMeta\x12G\n" +
	"\x03err\x18\x01 \x01(\v25.solana.storage.GeyserConfirmedBlock.TransactionErrorR\x03err\x12\x10\n" +
	"\x03fee\x18\x02 \x01(\x04R\x03fee\x12!\n" +
	"\fpre_balances\x18\x03 \x03(\x04R\vpreBalances\x12#\n" +
	"\rpost_balances\x18\x04 \x03(\x04R\fpostBalances\x12e\n" +
	"\x12inner_instructions\x18\x05 \x03(\v26.solana.storage.GeyserConfirmedBlock.InnerInstructionsR\x11innerInstructions\x126\n" +
	"\x17inner_instructions_none\x18\n" +
	" \x01(\bR\x15innerInstructionsNone\x12!\n" +
	"\flog_messages\x18\x06 \x03(\tR\vlogMessages\x12*\n" +
	"\x11log_messages_none\x18\v \x01(\bR\x0flogMessagesNone\x12_\n" +
	"\x12pre_token_balances\x18\a \x03(\v21.solana.storage.GeyserConfirmedBlock.TokenBalanceR\x10preTokenBalances\x12a\n" +
	"\x13post_token_balances\x18\b \x03(\v21.solana.storage.GeyserConfirmedBlock.TokenBalanceR\x11postTokenBalances\x12K\n" +
	"\arewards\x18\t \x03(\v21.solana.storage.GeyserConfirmedBlock.GeyserRewardR\arewards\x12:\n" +
	"\x19loaded_writable_addresses\x18\f \x03(\fR\x17loadedWritableAddresses\x12:\n" +
	"\x19loaded_readonly_addresses\x18\r \x03(\fR\x17loadedReadonlyAddresses\x12P\n" +
	"\vreturn_data\x18\x0e \x01(\v2/.solana.storage.GeyserConfirmedBlock.ReturnDataR\n" +
	"returnData\x12(\n" +
	"\x10return_data_none\x18\x0f \x01(\bR\x0ereturnDataNone\x129\n" +
	"\x16compute_units_consumed\x18\x10 \x01(\x04H\x00R\x14computeUnitsConsumed\x88\x01\x01B\x19\n" +
	"\x17_compute_units_consumed\"$\n" +
	"\x10TransactionError\x12\x10\n" +
	"\x03err\x18\x01 \x01(\fR\x03err\"\x84\x01\n" +
	"\x11InnerInstructions\x12\x14\n" +
	"\x05index\x18\x01 \x01(\rR\x05index\x12Y\n" +
	"\finstructions\x18\x02 \x03(\v25.solana.storage.GeyserConfirmedBlock.InnerInstructionR\finstructions\"\xa5\x01\n" +
	"\x10InnerInstruction\x12(\n" +
	"\x10program_id_index\x18\x01 \x01(\rR\x0eprogramIdIndex\x12\x1a\n" +
	"\baccounts\x18\x02 \x01(\fR\baccounts\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x12&\n" +
	"\fstack_height\x18\x04 \x01(\rH\x00R\vstackHeight\x88\x01\x01B\x0f\n" +
	"\r_stack_height\"o\n" +
	"\x13CompiledInstruction\x12(\n" +
	"\x10program_id_index\x18\x01 \x01(\rR\x0eprogramIdIndex\x12\x1a\n" +
	"\baccounts\x18\x02 \x01(\fR\baccounts\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\"\xd8\x01\n" +
	"\fTokenBalance\x12#\n" +
	"\raccount_index\x18\x01 \x01(\rR\faccountIndex\x12\x12\n" +
	"\x04mint\x18\x02 \x01(\tR\x04mint\x12Z\n" +
	"\x0fui_token_amount\x18\x03 \x01(\v22.solana.storage.GeyserConfirmedBlock.UiTokenAmountR\ruiTokenAmount\x12\x14\n" +
	"\x05owner\x18\x04 \x01(\tR\x05owner\x12\x1d\n" +
	"\n" +
	"program_id\x18\x05 \x01(\tR\tprogramId\"\x8a\x01\n" +
	"\rUiTokenAmount\x12\x1b\n" +
	"\tui_amount\x18\x01 \x01(\x01R\buiAmount\x12\x1a\n" +
	"\bdecimals\x18\x02 \x01(\rR\bdecimals\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\tR\x06amount\x12(\n" +
	"\x10ui_amount_string\x18\x04 \x01(\tR\x0euiAmountString\"?\n" +
	"\n" +
	"ReturnData\x12\x1d\n" +
	"\n" +
	"program_id\x18\x01 \x01(\fR\tprogramId\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"\xdd\x01\n" +
	"\fGeyserReward\x12\x16\n" +
	"\x06pubkey\x18\x01 \x01(\tR\x06pubkey\x12\x1a\n" +
	"\blamports\x18\x02 \x01(\x03R\blamports\x12!\n" +
	"\fpost_balance\x18\x03 \x01(\x04R\vpostBalance\x12V\n" +
	"\vreward_type\x18\x04 \x01(\x0e25.solana.storage.GeyserConfirmedBlock.GeyserRewardTypeR\n" +
	"rewardType\x12\x1e\n" +
	"\n" +
	"commission\x18\x05 \x01(\tR\n" +
	"commission\"\xb7\x01\n" +
	"\rGeyserRewards\x12K\n" +
	"\arewards\x18\x01 \x03(\v21.solana.storage.GeyserConfirmedBlock.GeyserRewardR\arewards\x12Y\n" +
	"\x0enum_partitions\x18\x02 \x01(\v22.solana.storage.GeyserConfirmedBlock.NumPartitionsR\rnumPartitions\"-\n" +
	"\rUnixTimestamp\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\"0\n" +
	"\vBlockHeight\x12!\n" +
	"\fblock_height\x18\x01 \x01(\x04R\vblockHeight\"6\n" +
	"\rNumPartitions\x12%\n" +
	"\x0enum_partitions\x18\x01 \x01(\x04R\rnumPartitions*O\n" +
	"\x10GeyserRewardType\x12\x0f\n" +
	"\vUnspecified\x10\x00\x12\a\n" +
	"\x03Fee\x10\x01\x12\b\n" +
	"\x04Rent\x10\x02\x12\v\n" +
	"\aStaking\x10\x03\x12\n" +
	"\n" +
	"\x06Voting\x10\x04B*Z(github.com/iqbalbaharum/solana-protos/pbb\x06proto3"

var (
	file_solana_storage_proto_rawDescOnce sync.Once
	file_solana_storage_proto_rawDescData []byte
)

func file_solana_storage_proto_rawDescGZIP() []byte {
	file_solana_storage_proto_rawDescOnce.Do(func() {
		file_solana_storage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_solana_storage_proto_rawDesc), len(file_solana_storage_proto_rawDesc)))
	})
	return file_solana_storage_proto_rawDescData
}

var file_solana_storage_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_solana_storage_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_solana_storage_proto_goTypes = []any{
	(GeyserRewardType)(0),             // 0: solana.storage.GeyserConfirmedBlock.GeyserRewardType
	(*GeyserConfirmedBlock)(nil),      // 1: solana.storage.GeyserConfirmedBlock.GeyserConfirmedBlock
	(*ConfirmedTransaction)(nil),      // 2: solana.storage.GeyserConfirmedBlock.ConfirmedTransaction
	(*Transaction)(nil),               // 3: solana.storage.GeyserConfirmedBlock.Transaction
	(*Message)(nil),                   // 4: solana.storage.GeyserConfirmedBlock.Message
	(*MessageHeader)(nil),             // 5: solana.storage.GeyserConfirmedBlock.MessageHeader
	(*MessageAddressTableLookup)(nil), // 6: solana.storage.GeyserConfirmedBlock.MessageAddressTableLookup
	(*TransactionStatusMeta)(nil),     // 7: solana.storage.GeyserConfirmedBlock.TransactionStatusMeta
	(*TransactionError)(nil),          // 8: solana.storage.GeyserConfirmedBlock.TransactionError
	(*InnerInstructions)(nil),         // 9: solana.storage.GeyserConfirmedBlock.InnerInstructions
	(*InnerInstruction)(nil),          // 10: solana.storage.GeyserConfirmedBlock.InnerInstruction
	(*CompiledInstruction)(nil),       // 11: solana.storage.GeyserConfirmedBlock.CompiledInstruction
	(*TokenBalance)(nil),              // 12: solana.storage.GeyserConfirmedBlock.TokenBalance
	(*UiTokenAmount)(nil),             // 13: solana.storage.GeyserConfirmedBlock.UiTokenAmount
	(*ReturnData)(nil),                // 14: solana.storage.GeyserConfirmedBlock.ReturnData
	(*GeyserReward)(nil),              // 15: solana.storage.GeyserConfirmedBlock.GeyserReward
	(*GeyserRewards)(nil),             // 16: solana.storage.GeyserConfirmedBlock.GeyserRewards
	(*UnixTimestamp)(nil),             // 17: solana.storage.GeyserConfirmedBlock.UnixTimestamp
	(*BlockHeight)(nil),               // 18: solana.storage.GeyserConfirmedBlock.BlockHeight
	(*NumPartitions)(nil),             // 19: solana.storage.GeyserConfirmedBlock.NumPartitions
}
var file_solana_storage_proto_depIdxs = []int32{
	2,  // 0: solana.storage.GeyserConfirmedBlock.GeyserConfirmedBlock.transactions:type_name -> solana.storage.GeyserConfirmedBlock.ConfirmedTransaction
	15, // 1: solana.storage.GeyserConfirmedBlock.GeyserConfirmedBlock.rewards:type_name -> solana.storage.GeyserConfirmedBlock.GeyserReward
	17, // 2: solana.storage.GeyserConfirmedBlock.GeyserConfirmedBlock.block_time:type_name -> solana.storage.GeyserConfirmedBlock.UnixTimestamp
	18, // 3: solana.storage.GeyserConfirmedBlock.GeyserConfirmedBlock.block_height:type_name -> solana.storage.GeyserConfirmedBlock.BlockHeight
	19, // 4: solana.storage.GeyserConfirmedBlock.GeyserConfirmedBlock.num_partitions:type_name -> solana.storage.GeyserConfirmedBlock.NumPartitions
	3,  // 5: solana.storage.GeyserConfirmedBlock.ConfirmedTransaction.transaction:type_name -> solana.storage.GeyserConfirmedBlock.Transaction
	7,  // 6: solana.storage.GeyserConfirmedBlock.ConfirmedTransaction.meta:type_name -> solana.storage.GeyserConfirmedBlock.TransactionStatusMeta
	4,  // 7: solana.storage.GeyserConfirmedBlock.Transaction.message:type_name -> solana.storage.GeyserConfirmedBlock.Message
	5,  // 8: solana.storage.GeyserConfirmedBlock.Message.header:type_name -> solana.storage.GeyserConfirmedBlock.MessageHeader
	11, // 9: solana.storage.GeyserConfirmedBlock.Message.instructions:type_name -> solana.storage.GeyserConfirmedBlock.CompiledInstruction
	6,  // 10: solana.storage.GeyserConfirmedBlock.Message.address_table_lookups:type_name -> solana.storage.GeyserConfirmedBlock.MessageAddressTableLookup
	8,  // 11: solana.storage.GeyserConfirmedBlock.TransactionStatusMeta.err:type_name -> solana.storage.GeyserConfirmedBlock.TransactionError
	9,  // 12: solana.storage.GeyserConfirmedBlock.TransactionStatusMeta.inner_instructions:type_name -> solana.storage.GeyserConfirmedBlock.InnerInstructions
	12, // 13: solana.storage.GeyserConfirmedBlock.TransactionStatusMeta.pre_token_balances:type_name -> solana.storage.GeyserConfirmedBlock.TokenBalance
	12, // 14: solana.storage.GeyserConfirmedBlock.TransactionStatusMeta.post_token_balances:type_name -> solana.storage.GeyserConfirmedBlock.TokenBalance
	15, // 15: solana.storage.GeyserConfirmedBlock.TransactionStatusMeta.rewards:type_name -> solana.storage.GeyserConfirmedBlock.GeyserReward
	14, // 16: solana.storage.GeyserConfirmedBlock.TransactionStatusMeta.return_data:type_name -> solana.storage.GeyserConfirmedBlock.ReturnData
	10, // 17: solana.storage.GeyserConfirmedBlock.InnerInstructions.instructions:type_name -> solana.storage.GeyserConfirmedBlock.InnerInstruction
	13, // 18: solana.storage.GeyserConfirmedBlock.TokenBalance.ui_token_amount:type_name -> solana.storage.GeyserConfirmedBlock.UiTokenAmount
	0,  // 19: solana.storage.GeyserConfirmedBlock.GeyserReward.reward_type:type_name -> solana.storage.GeyserConfirmedBlock.GeyserRewardType
	15, // 20: solana.storage.GeyserConfirmedBlock.GeyserRewards.rewards:type_name -> solana.storage.GeyserConfirmedBlock.GeyserReward
	19, // 21: solana.storage.GeyserConfirmedBlock.GeyserRewards.num_partitions:type_name -> solana.storage.GeyserConfirmedBlock.NumPartitions
	22, // [22:22] is the sub-list for method output_type
	22, // [22:22] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_solana_storage_proto_init() }
func file_solana_storage_proto_init() {
	if File_solana_storage_proto != nil {
		return
	}
	file_solana_storage_proto_msgTypes[6].OneofWrappers = []any{}
	file_solana_storage_proto_msgTypes[9].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_solana_storage_proto_rawDesc), len(file_solana_storage_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_solana_storage_proto_goTypes,
		DependencyIndexes: file_solana_storage_proto_depIdxs,
		EnumInfos:         file_solana_storage_proto_enumTypes,
		MessageInfos:      file_solana_storage_proto_msgTypes,
	}.Build()
	File_solana_storage_proto = out.File
	file_solana_storage_proto_goTypes = nil
	file_solana_storage_proto_depIdxs = nil
}
